version: '3.8'

services:

  db:
    container_name: db
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: example

  backend:
    container_name: backend
    build:
      context: .
    ports:
      - "8000:8000"
    environment:
      - "POSTGRES_DB_SERVER_ADDRESS=db"
      - "POSTGRES_DB_SERVER_PORT=5432"
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=example"
    depends_on:
      - db
    volumes:
      - "./src:/app/src"
